package ch.heigvd.res.lab00;

import org.junit.Assert;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

/**
 *       *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author Labinot Rashiti
 */
public class HarmonicaTest {

  
  @Test
  public void thereShouldBeAnIInstrumentInterfaceAndAHarmonicaClass() {
    IInstrument harmonica = new Harmonica();
    assertNotNull(harmonica);
  }
  
  @Test
  public void itShouldBePossibleToPlayAnInstrument() {
    IInstrument harmonica = new Harmonica();
    String sound = harmonica.play();
    assertNotNull(sound);
  }
  
  @Test
  public void aHarmonicaShouldMakeTouet() {
    IInstrument harmonica = new Harmonica();
    String sound = harmonica.play();
    Assert.assertEquals("touet", sound);
  }
  
  @Test
  public void aHarmonicaShouldBeLouderThanAFlute() {
    IInstrument harmonica = new Harmonica();
    IInstrument flute = new Flute();
    int harmonicaVolume = harmonica.getSoundVolume();
    int fluteVolume = flute.getSoundVolume();
    Assert.assertTrue(harmonicaVolume > fluteVolume);
  }

  @Test
  public void aHarmonicaShouldBeSilver() {
    IInstrument harmonica = new Harmonica();
    String color = harmonica.getColor();
    Assert.assertEquals("silver", color);
  }
  
 
}
